all: hw1-inst1 hw1-inst2 hw1-inst3

hw1-inst1:
	python3 hw1.py 60 data/hw1-inst1.txt > hw1-soln1.txt

hw1-inst2:
	python3 hw1.py 60 data/hw1-inst2.txt > hw1-soln2.txt

hw1-inst3:
	python3 hw1.py 60 data/hw1-inst3.txt > hw1-soln3.txt
